name: Build Haxe Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4


      - name: Set up Haxe, Install Android SDK, NDK, JDK, and Build
        run: |
          # Install OpenJDK
          ls
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          
          # Download and install Android SDK command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O commandlinetools.zip
          mkdir -p android-sdk/cmdline-tools
          unzip commandlinetools.zip -d android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
          
          # Set environment variables
          export ANDROID_SDK_ROOT=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          
          # Install required Android SDK components
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk-bundle"
          
          # Set up Haxe
          haxelib install lime
          haxelib install hxcpp
          haxelib install flxsvg 1.0.2
          haxelib install flixel 5.8.0 
          haxelib install openfl 9.3.4
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime setup android
          haxelib run lime setup html5

          # Build for Android
          haxelib run lime build android 
          
          # Build for HTML5
          haxelib run lime build html5 

      - name: Upload Android Build
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: export/android/bin/app.apk

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v2
        with:
          name: html5-build
          path: export/html5/bin
