name: Build Haxe Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haxe and Install Dependencies
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.2.5"
      
      - name: Install Libraries and Build for Android
        run: |
          haxelib install lime
          haxelib install hxcpp
          haxelib install flxsvg 1.0.2
          haxelib install flixel 5.8.0 
          haxelib install openfl 9.3.4
          haxelib install flixel-addons 3.2.3 
          haxelib run lime build android -final

      - name: Install Libraries and Build for HTML5
        run: |
          haxelib install lime
          haxelib install hxcpp
          haxelib install flxsvg 1.0.2
          haxelib install flixel 5.8.0 
          haxelib install openfl 9.3.4
          haxelib install flixel-addons 3.2.3 
          haxelib run lime build html5 -final

      - name: Upload Android Build
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: export/android/bin/app.apk

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v2
        with:
          name: html5-build
          path: export/html5/bin
