name: Build Haxe Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Haxelib
        uses: actions/cache@v3
        with:
          path: |
            ~/haxelib
            ~/.haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/project.xml') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Setup Haxe libraries and build
        run: |
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install hxcpp --quiet
          haxelib install flxsvg 1.0.2 --quiet
          haxelib install flixel 5.8.0 --quiet
          haxelib install openfl 9.3.4 --quiet
          lime setup flixel

          lime setup android -y
          lime setup html5 -y
          
          # Display installed Haxelib libraries for debugging
          haxelib list

          # Build for Android
          lime build android -verbose -y
          
          # Build for HTML5
          lime build html5 -verbose -y

      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v3
        with:
          name: html5-build
          path: export/release/html5/bin