name: Build Haxe Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.2.5"
          install-libraries: |
            lime
            hxcpp
            flxsvg:1.0.2

      - name: Build Android
        run: haxelib run lime build android -final

  build-html5:
    name: Build for HTML5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.2.5"
          install-libraries: |
            lime
            flxsvg:1.0.2

      - name: Build HTML5
        run: haxelib run lime build html5 -final

  artifact-android:
    name: Upload Android Build
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: export/android/bin/app.apk

  artifact-html5:
    name: Upload HTML5 Build
    needs: build-html5
    runs-on: ubuntu-latest
    steps:
      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v2
        with:
          name: html5-build
          path: export/html5/bin
